# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
