# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160421_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ticket',
            field=models.IntegerField(default=0),
        ),
    ]
